src/DinosaursPark.WebApplication/Controllers/DinosaursController.cs
using DinosaursPark.Contracts.Services;
using DinosaursPark.WebApplication.Requests;
using DinosaursPark.WebApplication.Responses;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace DinosaursPark.WebApplication.Controllers
{
    public class DinosaursController : Controller
    {
        private readonly IDinosaursService _dinoService;

        public DinosaursController(IDinosaursService dinoService)
        {
            _dinoService = dinoService ?? throw new ArgumentNullException(nameof(dinoService));
        }

        public ViewResult Index()
        {
            return View();
        }

        [HttpGet("/get")]
        public async Task<IActionResult> Get(GetByIdRequest request)
        {
            var result = await _dinoService.Get<DinosaurResponse>(request.Id);
            return Ok(result);
        }

        [HttpGet("/all")]
        public async Task<IActionResult> GetAll(PagingRequest request)
        {
            var result = await _dinoService.Get<SimpleDinosaurResponse>(request.PageNumber, request.PageSize);
            return Ok(result);
        }

        [HttpDelete]
        public async Task<IActionResult> ClearInformation()
        {
            await _dinoService.DeleteAll();
            return NoContent();
        }
    }
}

src/DinosaursPark.WebApplication/Controllers/GenerationController.cs
using System;
using System.Threading.Tasks;
using DinosaursPark.Contracts.Services;
using DinosaursPark.WebApplication.Requests;
using Microsoft.AspNetCore.Mvc;

namespace DinosaursPark.WebApplication.Controllers
{
    [Route("generation")]
    public class GenerationController : Controller
    {
        private readonly IDataGenerator _generator;

        public GenerationController(IDataGenerator generator)
        {
            _generator = generator ?? throw new ArgumentNullException(nameof(generator));
        }

        public ViewResult Index()
        {
            return View();
        }

        [HttpPost("create")]
        [ProducesResponseType(200)]
        public async Task<IActionResult> Create(GenerationRequest request)
        {
            var result = await _generator.Generate(request.Data.SpeciesCount, request.Data.DinosaursCount);
            return Ok(result);
        }
    }
}

src/DinosaursPark.WebApplication/Controllers/InformationController.cs
using DinosaursPark.Contracts.Services;
using DinosaursPark.WebApplication.Requests;
using DinosaursPark.WebApplication.Responses;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace DinosaursPark.WebApplication.Controllers
{
    [Route("/information")]
    public class InformationController : Controller
    {
        private readonly IInformationService _informationService;

        public InformationController(IInformationService informationService)
        {
            _informationService = informationService ?? throw new ArgumentNullException(nameof(informationService));
        }

        [HttpGet]
        public ViewResult Index()
        {
            return View();
        }

        [HttpGet("park")]
        public async Task<IActionResult> LoadInfo()
        {
            var result = await _informationService.GetParkInfo<ParkInformationResponse>();
            return Ok(result);
        }

        [HttpGet("species")]
        public async Task<IActionResult> SpeciesInfo(PagingRequest request)
        {
            var result = await _informationService
                .GetSpeciesInfo<SpeciesInformationResponse>(request.PageNumber, request.PageSize);
            return Ok(result);
        }

        [HttpDelete]
        public async Task<IActionResult> ClearInformation()
        {
            await _informationService.DeleteAll();
            return NoContent();
        }
    }
}

src/DinosaursPark.WebApplication/Views/Dinosaurs/Index.cshtml
@{
    string title = "Наши динозавры";
    ViewData["Title"] = title;
}

<div class="text-center">
    <h1 class="display-4">@title</h1>
</div>

<script src="~/js/start.min.js" asp-append-version="true"></script>

<script type="text/babel" src="/js/components/modal.jsx"></script>
<script type="text/babel" src="/js/components/dinosaurCardModal.jsx"></script>
<script type="text/babel" src="/js/components/preview.jsx"></script>

<div id="no-data-alert" class="card"></div>

<div id="dinosaur-modal" class="modal fade"></div>
<div id="for-jsx"></div>
<div id="dinosaurs-area"></div>

<nav id="paging-nav"></nav>

src/DinosaursPark.WebApplication/Views/Generation/Index.cshtml
@{
    string title = "Создать";
    ViewData["Title"] = title;
}

<script src="~/js/generation.min.js" asp-append-version="true"></script>
<script type="text/babel" src="/js/components/generation.jsx"></script>

<div id="no-data-alert" class="card"></div>

src/DinosaursPark.WebApplication/Views/Information/Index.cshtml
@{
    string title = "Информация";
    ViewData["Title"] = title;
}

<div class="text-center">
    <h1 class="display-4">@title</h1>
</div>

<script src="~/js/info.min.js"></script>
<script type="text/babel" src="/js/components/parkInfo.jsx"></script>
<script type="text/babel" src="/js/components/modal.jsx"></script>
<script type="text/babel" src="~/js/components/deleteConfirmModal.jsx"></script>
<script type="text/babel" src="/js/components/speciesInfo.jsx"></script>

<div id="no-data-alert" class="card"></div>
<div id="delete-modal" class="modal fade"></div>

<div class="container-fluid">
    <div class="row">
        <div id="info-area" class="col-lg-5"></div>
        <div class="col-lg-6">
            <div id="species-info-area"></div>
            <nav id="paging-nav"></nav>
        </div>
    </div>
</div>

src/DinosaursPark.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DinosaursPark</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/16.8.0/umd/react.development.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.0/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
    
    <script src="~/js/main.min.js"></script>
    
    <script type="text/babel" src="/js/components/paging.jsx"></script>
    
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/main.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Dinosaurs" asp-action="Index">DinosaursPark</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Information" asp-action="Index">Информация</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - DinosaursPark
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>    
    @RenderSection("Scripts", required: false)
</body>
</html>